export const CLEAR_AUTH = 'CLEAR_AUTH'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER = 'SET_USER'
export const SET_USER_NAME = 'SET_USER_NAME'
export const MILLAN_EXAMPLE = 'MILLAN_EXAMPLE'
